### ISSUE TITLE
support for :skip and xit

### ISSUE THREAD

**Issue by timoschilling** [lovewithfood/rubocop-rspec-focused#8]
It would be great to have support for `:skip` and `xit` and co.

**Comment by htanata** [comment]
Thanks for your suggestion, @timoschilling. This gem only does one thing, or else it'll have to change its name too. :)

Maybe you can request the feature on the more general [rubocop-rspec](https://github.com/backus/rubocop-rspec) instead. It also has support for [detecting focused specs](https://github.com/backus/rubocop-rspec/blob/53f42c3e4e7f1182ef0c15f5cb5452c2c8a84628/config/default.yml#L153).

**Comment by timoschilling** [comment]
thanks for the hint
